name: Build & Publish Release APK

on:
  workflow_dispatch:
  push:

    tags:

      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Android Apk CI
        uses: yuanjinsongquyi/action_android_build@v1
