name: Build & Publish Release APK

on:
  workflow_dispatch:
  push:

    tags:

      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read Android Build Gradle File
        uses: wu-json/read-android-build-gradle@v1.0
        with:
          path: 'build.gradle'
